service: talktoevroc

image: oloflarsson/talktoevroc

deploy_timeout: 20

servers:
  web:
    - 135.181.151.248

proxy:
  ssl: true
  host: talktoevroc.olof.tech
  app_port: 7860
  healthcheck:
    path: /
    interval: 1
    timeout: 20

registry:
  server: ghcr.io
  username: oloflarsson
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  # Use local directory instead of git clone (includes uncommitted dist/)
  context: .

env:
  secret:
    - EVROC_API_KEY_STT
    - EVROC_API_KEY_LLM

aliases:
  shell: app exec --interactive --reuse "bash"
  reclaim: 'server exec "docker system prune -a -f"'
  logs: app logs -n 500
